import turtle
screen = turtle.Screen()
my_turtle = turtle.Turtle()

# Set up the window
screen.setup(800, 600)

# Set the canvas size
screen.screensize(1000, 800) # do not include if using trinket.io

# Exercise a
my_turtle.circle(50)

# Exercise b
my_turtle.fd(200)
my_turtle.left(90)
my_turtle.fd(200)
my_turtle.left(90)
my_turtle.fd(200)
my_turtle.left(90)
my_turtle.fd(200)
my_turtle.left(90)

# Exercise c
my_turtle.fd(200)
my_turtle.left(120)
my_turtle.fd(200)
my_turtle.left(120)
my_turtle.fd(200)
my_turtle.left(120)

# Exercise d
my_turtle.pencolor("blue")
my_turtle.fillcolor("red")
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)
my_turtle.fd(75)
my_turtle.left(36)

# Exercise e
my_turtle.penup()
my_turtle.right(90)
my_turtle.fd(150)
my_turtle.left(90)
my_turtle.pendown()
my_turtle.fillcolor("#870000")
my_turtle.begin_fill()
my_turtle.circle(200)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.left(90)
my_turtle.fd(40)
my_turtle.right(90)
my_turtle.pendown()
my_turtle.fillcolor("#f0f0f0")
my_turtle.begin_fill()
my_turtle.circle(160)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.left(90)
my_turtle.fd(40)
my_turtle.right(90)
my_turtle.pendown()
my_turtle.fillcolor("#870000")
my_turtle.begin_fill()
my_turtle.circle(120)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.left(90)
my_turtle.fd(40)
my_turtle.right(90)
my_turtle.pendown()
my_turtle.fillcolor("#002d5c")
my_turtle.begin_fill()
my_turtle.circle(80)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(-20, 75)
my_turtle.setheading(0)
my_turtle.pendown()

my_turtle.fillcolor("#f0f0f0")
my_turtle.begin_fill()
my_turtle.left(72)
my_turtle.fd(60)
my_turtle.right(144)
my_turtle.fd(60)
my_turtle.left(72)
my_turtle.fd(60)
my_turtle.right(144)
my_turtle.fd(60)
my_turtle.left(72)
my_turtle.fd(60)
my_turtle.right(144)
my_turtle.fd(60)
my_turtle.left(72)
my_turtle.fd(60)
my_turtle.right(144)
my_turtle.fd(60)
my_turtle.left(72)
my_turtle.fd(60)
my_turtle.right(144)
my_turtle.fd(60)
my_turtle.end_fill()

turtle.done()